del *.obj /s
del *.sbr /s
del *.pch /s
del *.ilk /s
del *.res /s
del *.ncb /s
del *.suo /s
del *.map /s
del *.pdb /s
del buildlog.htm /s
del *.log /s
del *.idb /s
del *.exp /s
del *.dep /s
del *.manifest /s
del *.user /s
del *.sdf /s
del *.ipch /s